overworld:
  enable: true
  enable-old: true
  height: 128
  biome: true
  block:
    - [1, 0]
    - [1, 0]
    - [1, 0]
    - [1, 1]
    - [1, 3]
    - [1, 5]
    - [2, 0]
    - [2, 0]
    - [3, 0]
    - [3, 0]
    - [3, 0]
    - [3, 0]
    - [4, 0]
    - [9, 0]
    - [11, 0]
    - [12, 0]
    - [12, 1]
    - [13, 0]
    - [14, 0]
    - [15, 0]
    - [16, 0]
    - [17, 0]
    - [17, 1]
    - [17, 2]
    - [17, 3]
    - [18, 0]
    - [18, 1]
    - [18, 2]
    - [18, 3]
    - [19, 0]
    - [20, 0]
    - [21, 0]
    - [24, 0]
    - [30, 0]
    - [48, 0]
    - [52, 0]
#    - [54, 4]
    - [56, 0]
    - [73, 0]
    - [79, 0]
    - [80, 0]
    - [82, 0]
    - [86, 0]
    - [97, 0]
    - [97, 1]
    - [97, 2]
    - [97, 3]
    - [97, 4]
    - [97, 5]
    - [98, 0]
    - [98, 1]
    - [98, 2]
    - [99, 14]
    - [100, 14]
    - [103, 0]
    - [110, 0]
    - [129, 0]
    - [159, 0]
    - [161, 0]
    - [161, 1]
    - [162, 0]
    - [162, 1]
    - [165, 0]
    - [168, 0]
    - [169, 0]
    - [170, 0]
    - [174, 0]
    - [179, 0]
    - [198, 0]
    - [216, 0]
    - [243, 0]
#    - [266, 0]
#    - [387, 0]
#    - [410, 0]
nether:
  enable: true
  height: 128
  block:
    - [11, 0]
    - [13, 0]
    - [49, 0]
    - [52, 0]
#    - [54, 4]
    - [87, 0]
    - [87, 0]
    - [87, 0]
    - [87, 0]
    - [87, 0]
    - [87, 0]
    - [87, 0]
    - [87, 0]
    - [88, 0]
    - [88, 0]
    - [89, 0]
    - [112, 0]
    - [113, 0]
    - [114, 0]
    - [153, 0]
    - [155, 0]
    - [156, 0]
    - [213, 0]
    - [214, 0]
    - [215, 0]
end:
  enable: true
  height: 128
  block:
    - [49, 0]
    - [52, 0]
#    - [54, 4]
    - [121, 0]
    - [121, 0]
    - [121, 0]
    - [121, 0]
    - [121, 0]
    - [121, 0]
    - [121, 0]
    - [121, 0]
    - [121, 0]
    - [121, 0]
    - [130, 0]
    - [200, 0]
    - [201, 0]
    - [203, 0]
    - [205, 0]
    - [206, 0]
    - [208, 0]
    - [209, 0]
    - [240, 0]
    - [241, 10]