main: cn.wode490390.nukkit.skygridgenerator.SGGenerator
name: "SkyGridGenerator"
author: "wode490390"
description: "SkyGrid generator plugin for Nukkit"
website: "http://wode490390.cn/"
version: "1.0.0"
api: ["1.0.0"]
load: STARTUP